apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: result
  name: result
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: result
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}