# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  vote: "__vote_image__"
  result: "__result_image__"
  worker: "__worker_image__"


env: bunnyshell
replicas: 1
unique: xxxxxx
ingress:
    className: bns-nginx
db:
  user: postgres
  password: postgres